### ISSUE TITLE
SMTP setup during installation/configuration

### ISSUE THREAD

**Issue by frankstrater** [beeldengeluid/extending-peertube#7]
A working SMTP service is required for email being sent for features like password reset, contact admin form, signup verification. PeerTube itself does not contain or recommend a SMTP service. This might be a problem if you don't have a SMTP service available like one you get by registering a domain at a (mail) hosting provider.

Questions: 

- are there any free/libre SMTP-relay services that can be recommended?
- what are the pros/cons of setting up SMTP yourself? Exim, Postfix, Sendmail, and Qmail
- add some Dutch flavour by using Wietse Venema's Postfix?
- are non-corporate MTA's even viable these days? or is it all marked as spam?

Reference: [closed PeerTube issues on SMTP](https://github.com/Chocobozzz/PeerTube/issues?q=is%3Aissue+smtp+is%3Aclosed)

**Comment by frankstrater** [comment]
### smtp.gmail.com

Although there are some downsides in using a "free" Gmail account for access to a non-blacklisted SMTP relay, it's quite easy to setup, although it's limited to sending 2000 messages per day.

- Generate an app password with https://myaccount.google.com/u/1/apppasswords
- Add the following configuration in /var/www/peertube/config/production.yaml

```
# SMTP server to send emails
smtp:
  # smtp or sendmail
  transport: smtp
  # Path to sendmail command. Required if you use sendmail transport
  sendmail: null
  hostname: 'smtp.gmail.com'
  port: 587 # If you use StartTLS: 587
  username: 'youraccount@gmail.com'
  password: 'yourapppassword'
  tls: false # If you use StartTLS: false
  disable_starttls: false
  ca_file: null # Used for self signed certificates
  from_address: 'youraccount@gmail.com'
```

See this Google support article 'Send email from a printer, scanner or app' in the section 'Other setup options' > 'Use the Gmail SMTP server': https://support.google.com/a/answer/176600?hl=en
